// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Layout → Social links*
 */
export interface LayoutDocumentDataSocialLinksItem {
	/**
	 * Platform field in *Layout → Social links*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.social_links[].platform
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	platform: prismic.SelectField<"LinkedIn" | "Instagram" | "Twitter" | "YouTube" | "Other">;
	
	/**
	 * URL field in *Layout → Social links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: https://...
	 * - **API ID Path**: layout.social_links[].url
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Layout → Nav links*
 */
export interface LayoutDocumentDataNavLinksItem {
	/**
	 * Label field in *Layout → Nav links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Services
	 * - **API ID Path**: layout.nav_links[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Link field in *Layout → Nav links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Page or URL
	 * - **API ID Path**: layout.nav_links[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Layout → Footer links*
 */
export interface LayoutDocumentDataFooterLinksItem {
	/**
	 * Label field in *Layout → Footer links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Link text
	 * - **API ID Path**: layout.footer_links[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Link field in *Layout → Footer links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.footer_links[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
	/**
	 * Header logo field in *Layout*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.header_logo
	 * - **Tab**: Site config
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	header_logo: prismic.ImageField<never>;
	
	/**
	 * Footer logo (optional) field in *Layout*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.footer_logo
	 * - **Tab**: Site config
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	footer_logo: prismic.ImageField<never>;
	
	/**
	 * Favicon (optional) field in *Layout*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.favicon
	 * - **Tab**: Site config
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	favicon: prismic.ImageField<never>;
	
	/**
	 * Aberdeen address field in *Layout*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.aberdeen_address
	 * - **Tab**: Site config
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	aberdeen_address: prismic.RichTextField;
	
	/**
	 * Aberdeen phone field in *Layout*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: +44 (0) 1224 790970
	 * - **API ID Path**: layout.aberdeen_phone
	 * - **Tab**: Site config
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	aberdeen_phone: prismic.KeyTextField;
	
	/**
	 * Aberdeen email field in *Layout*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: info@microneagle.com
	 * - **API ID Path**: layout.aberdeen_email
	 * - **Tab**: Site config
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	aberdeen_email: prismic.KeyTextField;
	
	/**
	 * Aberdeen opening hours field in *Layout*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Mon–Fri: 8am – 5pm
	 * - **API ID Path**: layout.aberdeen_hours
	 * - **Tab**: Site config
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	aberdeen_hours: prismic.KeyTextField;
	
	/**
	 * Houston address field in *Layout*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.houston_address
	 * - **Tab**: Site config
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	houston_address: prismic.RichTextField;
	
	/**
	 * Houston phone field in *Layout*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: +1 713 812 0720
	 * - **API ID Path**: layout.houston_phone
	 * - **Tab**: Site config
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	houston_phone: prismic.KeyTextField;
	
	/**
	 * Houston email field in *Layout*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.houston_email
	 * - **Tab**: Site config
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	houston_email: prismic.KeyTextField;
	
	/**
	 * Phone menu (optional) field in *Layout*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Press 1 for Sales, 2 for Repair...
	 * - **API ID Path**: layout.phone_menu
	 * - **Tab**: Site config
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	phone_menu: prismic.RichTextField;
	
	/**
	 * Primary email (optional) field in *Layout*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Default for forms
	 * - **API ID Path**: layout.primary_email
	 * - **Tab**: Site config
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	primary_email: prismic.KeyTextField;
	
	/**
	 * Social links field in *Layout*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.social_links[]
	 * - **Tab**: Site config
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	social_links: prismic.GroupField<Simplify<LayoutDocumentDataSocialLinksItem>>;/**
	 * Nav links field in *Layout*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.nav_links[]
	 * - **Tab**: Header & navigation
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	nav_links: prismic.GroupField<Simplify<LayoutDocumentDataNavLinksItem>>;/**
	 * Footer links field in *Layout*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.footer_links[]
	 * - **Tab**: Footer
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	footer_links: prismic.GroupField<Simplify<LayoutDocumentDataFooterLinksItem>>;
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<LayoutDocumentData>, "layout", Lang>;

type PageDocumentDataSlicesSlice = HeroSlice | MainPathwaysSlice | CoreServicesSlice | IndustryApplicationsSlice | WhyMicronEagleSlice | CertificationsPartnersSlice | TestimonialsSlice | CtaBandSlice | RichTextSlice | FaqSlice | TeamSectionSlice | BlogGridSlice | MainPathwaysV2Slice | CoreServicesV2Slice | IndustryApplicationsV2Slice | WhyMicronEagleV2Slice | CertificationsPartnersV2Slice | TestimonialsV2Slice | CtaBandV2Slice | StatsBandSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Section field in *Page*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: Choose section for nav grouping
	 * - **API ID Path**: page.section
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	section: prismic.SelectField<"Home" | "Services on-site" | "Services and Repairs" | "Spare-parts" | "About" | "Others" | "contact">;
	
	/**
	 * Intro / short description field in *Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Optional for listing cards
	 * - **API ID Path**: page.intro
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	intro: prismic.RichTextField;
	
	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;/**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = LayoutDocument | PageDocument;

/**
 * Primary content in *BlogGrid → Default → Primary*
 */
export interface BlogGridSliceDefaultPrimary {
	/**
	 * Eyebrow label (optional) field in *BlogGrid → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Insights
	 * - **API ID Path**: blog_grid.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;
	
	/**
	 * Section heading field in *BlogGrid → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Latest from Micron Eagle
	 * - **API ID Path**: blog_grid.default.primary.section_heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	section_heading: prismic.RichTextField;
	
	/**
	 * View all label (optional) field in *BlogGrid → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: All articles
	 * - **API ID Path**: blog_grid.default.primary.view_all_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	view_all_label: prismic.KeyTextField;
	
	/**
	 * View all link (optional) field in *BlogGrid → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_grid.default.primary.view_all_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	view_all_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *BlogGrid → Items*
 */
export interface BlogGridSliceDefaultItem {
	/**
	 * Cover image field in *BlogGrid → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_grid.items[].cover_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	cover_image: prismic.ImageField<never>;
	
	/**
	 * Category tag field in *BlogGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Hydraulic Repair
	 * - **API ID Path**: blog_grid.items[].category
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	category: prismic.KeyTextField;
	
	/**
	 * Publication date field in *BlogGrid → Items*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_grid.items[].date
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	date: prismic.DateField;
	
	/**
	 * Article title field in *BlogGrid → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_grid.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Excerpt field in *BlogGrid → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_grid.items[].excerpt
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	excerpt: prismic.RichTextField;
	
	/**
	 * Link to article field in *BlogGrid → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_grid.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Read more label (optional) field in *BlogGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Read article
	 * - **API ID Path**: blog_grid.items[].read_more_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	read_more_label: prismic.KeyTextField;
}

/**
 * Default variation for BlogGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: 3-column article grid with cover image, category, date and excerpt
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogGridSliceDefault = prismic.SharedSliceVariation<"default", Simplify<BlogGridSliceDefaultPrimary>, Simplify<BlogGridSliceDefaultItem>>;

/**
 * Slice variation for *BlogGrid*
 */
type BlogGridSliceVariation = BlogGridSliceDefault

/**
 * BlogGrid Shared Slice
 *
 * - **API ID**: `blog_grid`
 * - **Description**: Grid of blog/news article cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogGridSlice = prismic.SharedSlice<"blog_grid", BlogGridSliceVariation>;

/**
 * Primary content in *CertificationsPartners → Default → Primary*
 */
export interface CertificationsPartnersSliceDefaultPrimary {
	/**
	 * Headline (optional) field in *CertificationsPartners → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Certifications & Partners
	 * - **API ID Path**: certifications_partners.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	headline: prismic.RichTextField;
}

/**
 * Primary content in *CertificationsPartners → Items*
 */
export interface CertificationsPartnersSliceDefaultItem {
	/**
	 * Logo / image field in *CertificationsPartners → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: certifications_partners.items[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Link (optional) field in *CertificationsPartners → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: certifications_partners.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Label field in *CertificationsPartners → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: ISO 9001
	 * - **API ID Path**: certifications_partners.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
}

/**
 * Default variation for CertificationsPartners Slice
 *
 * - **API ID**: `default`
 * - **Description**: Repeatable logo/label items
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CertificationsPartnersSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CertificationsPartnersSliceDefaultPrimary>, Simplify<CertificationsPartnersSliceDefaultItem>>;

/**
 * Slice variation for *CertificationsPartners*
 */
type CertificationsPartnersSliceVariation = CertificationsPartnersSliceDefault

/**
 * CertificationsPartners Shared Slice
 *
 * - **API ID**: `certifications_partners`
 * - **Description**: Logos and short text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CertificationsPartnersSlice = prismic.SharedSlice<"certifications_partners", CertificationsPartnersSliceVariation>;

/**
 * Primary content in *CertificationsPartnersV2 → Default → Primary*
 */
export interface CertificationsPartnersV2SliceDefaultPrimary {
	/**
	 * Partners section label field in *CertificationsPartnersV2 → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Trusted Partners
	 * - **API ID Path**: certifications_partners_v2.default.primary.partners_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	partners_label: prismic.KeyTextField;
	
	/**
	 * Headline (optional) field in *CertificationsPartnersV2 → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: certifications_partners_v2.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	headline: prismic.RichTextField;
	
	/**
	 * Show ISO certifications? field in *CertificationsPartnersV2 → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: certifications_partners_v2.default.primary.show_iso_certs
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	show_iso_certs: prismic.BooleanField;
	
	/**
	 * ISO cert 1 (e.g. 9001:2015) field in *CertificationsPartnersV2 → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 9001:2015
	 * - **API ID Path**: certifications_partners_v2.default.primary.iso_cert_1
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	iso_cert_1: prismic.KeyTextField;
	
	/**
	 * ISO cert 2 (e.g. 14001:2015) field in *CertificationsPartnersV2 → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 14001:2015
	 * - **API ID Path**: certifications_partners_v2.default.primary.iso_cert_2
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	iso_cert_2: prismic.KeyTextField;
	
	/**
	 * ISO cert 3 (e.g. 45001:2018) field in *CertificationsPartnersV2 → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 45001:2018
	 * - **API ID Path**: certifications_partners_v2.default.primary.iso_cert_3
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	iso_cert_3: prismic.KeyTextField;
}

/**
 * Primary content in *CertificationsPartnersV2 → Items*
 */
export interface CertificationsPartnersV2SliceDefaultItem {
	/**
	 * Partner / brand logo field in *CertificationsPartnersV2 → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: certifications_partners_v2.items[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Partner name / label field in *CertificationsPartnersV2 → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Danfoss
	 * - **API ID Path**: certifications_partners_v2.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Link (optional) field in *CertificationsPartnersV2 → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: certifications_partners_v2.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for CertificationsPartnersV2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Logo strip with optional ISO cert badges
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CertificationsPartnersV2SliceDefault = prismic.SharedSliceVariation<"default", Simplify<CertificationsPartnersV2SliceDefaultPrimary>, Simplify<CertificationsPartnersV2SliceDefaultItem>>;

/**
 * Slice variation for *CertificationsPartnersV2*
 */
type CertificationsPartnersV2SliceVariation = CertificationsPartnersV2SliceDefault

/**
 * CertificationsPartnersV2 Shared Slice
 *
 * - **API ID**: `certifications_partners_v2`
 * - **Description**: Partner logos + ISO certification badges
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CertificationsPartnersV2Slice = prismic.SharedSlice<"certifications_partners_v2", CertificationsPartnersV2SliceVariation>;

/**
 * Primary content in *CoreServices → Default → Primary*
 */
export interface CoreServicesSliceDefaultPrimary {
	/**
	 * Section heading field in *CoreServices → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Core services
	 * - **API ID Path**: core_services.default.primary.section_heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	section_heading: prismic.RichTextField;
}

/**
 * Primary content in *CoreServices → Items*
 */
export interface CoreServicesSliceDefaultItem {
	/**
	 * Title field in *CoreServices → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: On-Site Hydraulic Services
	 * - **API ID Path**: core_services.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Description field in *CoreServices → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: core_services.items[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * Link to page field in *CoreServices → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: core_services.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Image (optional) field in *CoreServices → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: core_services.items[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for CoreServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Repeatable service cards with link to Page
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CoreServicesSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CoreServicesSliceDefaultPrimary>, Simplify<CoreServicesSliceDefaultItem>>;

/**
 * Slice variation for *CoreServices*
 */
type CoreServicesSliceVariation = CoreServicesSliceDefault

/**
 * CoreServices Shared Slice
 *
 * - **API ID**: `core_services`
 * - **Description**: Grid of service cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CoreServicesSlice = prismic.SharedSlice<"core_services", CoreServicesSliceVariation>;

/**
 * Primary content in *CoreServicesV2 → Default → Primary*
 */
export interface CoreServicesV2SliceDefaultPrimary {
	/**
	 * Section heading field in *CoreServicesV2 → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Core services
	 * - **API ID Path**: core_services_v2.default.primary.section_heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	section_heading: prismic.RichTextField;
}

/**
 * Primary content in *CoreServicesV2 → Items*
 */
export interface CoreServicesV2SliceDefaultItem {
	/**
	 * Title field in *CoreServicesV2 → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: On-Site Hydraulic Services
	 * - **API ID Path**: core_services_v2.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Description field in *CoreServicesV2 → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: core_services_v2.items[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * Link to page field in *CoreServicesV2 → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: core_services_v2.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Image (optional) field in *CoreServicesV2 → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: core_services_v2.items[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for CoreServicesV2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Repeatable service cards with link to Page
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CoreServicesV2SliceDefault = prismic.SharedSliceVariation<"default", Simplify<CoreServicesV2SliceDefaultPrimary>, Simplify<CoreServicesV2SliceDefaultItem>>;

/**
 * Slice variation for *CoreServicesV2*
 */
type CoreServicesV2SliceVariation = CoreServicesV2SliceDefault

/**
 * CoreServicesV2 Shared Slice
 *
 * - **API ID**: `core_services_v2`
 * - **Description**: Grid of service cards (variant)
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CoreServicesV2Slice = prismic.SharedSlice<"core_services_v2", CoreServicesV2SliceVariation>;

/**
 * Primary content in *CtaBand → Default → Primary*
 */
export interface CtaBandSliceDefaultPrimary {
	/**
	 * Headline field in *CtaBand → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Need parts? Need service?
	 * - **API ID Path**: cta_band.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	headline: prismic.RichTextField;
}

/**
 * Primary content in *CtaBand → Items*
 */
export interface CtaBandSliceDefaultItem {
	/**
	 * CTA label field in *CtaBand → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Need parts?
	 * - **API ID Path**: cta_band.items[].cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;
	
	/**
	 * CTA link field in *CtaBand → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_band.items[].cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for CtaBand Slice
 *
 * - **API ID**: `default`
 * - **Description**: Headline and repeatable CTAs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBandSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CtaBandSliceDefaultPrimary>, Simplify<CtaBandSliceDefaultItem>>;

/**
 * Slice variation for *CtaBand*
 */
type CtaBandSliceVariation = CtaBandSliceDefault

/**
 * CtaBand Shared Slice
 *
 * - **API ID**: `cta_band`
 * - **Description**: Final CTA strip
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBandSlice = prismic.SharedSlice<"cta_band", CtaBandSliceVariation>;

/**
 * Primary content in *CtaBandV2 → Default → Primary*
 */
export interface CtaBandV2SliceDefaultPrimary {
	/**
	 * Eyebrow (optional) field in *CtaBandV2 → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Get Started
	 * - **API ID Path**: cta_band_v2.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;
	
	/**
	 * Headline field in *CtaBandV2 → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Need parts? Need service?
	 * - **API ID Path**: cta_band_v2.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	headline: prismic.RichTextField;
	
	/**
	 * Subtext (optional) field in *CtaBandV2 → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_band_v2.default.primary.subtext
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtext: prismic.RichTextField;
}

/**
 * Primary content in *CtaBandV2 → Items*
 */
export interface CtaBandV2SliceDefaultItem {
	/**
	 * CTA label field in *CtaBandV2 → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Need parts?
	 * - **API ID Path**: cta_band_v2.items[].cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;
	
	/**
	 * CTA link field in *CtaBandV2 → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_band_v2.items[].cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for CtaBandV2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Headline and repeatable CTAs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBandV2SliceDefault = prismic.SharedSliceVariation<"default", Simplify<CtaBandV2SliceDefaultPrimary>, Simplify<CtaBandV2SliceDefaultItem>>;

/**
 * Slice variation for *CtaBandV2*
 */
type CtaBandV2SliceVariation = CtaBandV2SliceDefault

/**
 * CtaBandV2 Shared Slice
 *
 * - **API ID**: `cta_band_v2`
 * - **Description**: Final CTA strip (variant)
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBandV2Slice = prismic.SharedSlice<"cta_band_v2", CtaBandV2SliceVariation>;

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
	/**
	 * Eyebrow label (optional) field in *Faq → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: FAQ
	 * - **API ID Path**: faq.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;
	
	/**
	 * Section heading field in *Faq → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Common Questions
	 * - **API ID Path**: faq.default.primary.section_heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	section_heading: prismic.RichTextField;
	
	/**
	 * Subtext (optional) field in *Faq → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Can't find what you're looking for? Contact our team.
	 * - **API ID Path**: faq.default.primary.subtext
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtext: prismic.RichTextField;
	
	/**
	 * CTA label (optional) field in *Faq → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Contact us
	 * - **API ID Path**: faq.default.primary.cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;
	
	/**
	 * CTA link (optional) field in *Faq → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Faq → Items*
 */
export interface FaqSliceDefaultItem {
	/**
	 * Question field in *Faq → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: How long does a repair take?
	 * - **API ID Path**: faq.items[].question
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	question: prismic.KeyTextField;
	
	/**
	 * Answer field in *Faq → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq.items[].answer
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	answer: prismic.RichTextField;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Sidebar heading with expandable question/answer list
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<"default", Simplify<FaqSliceDefaultPrimary>, Simplify<FaqSliceDefaultItem>>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: FAQ accordion with sidebar heading
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Headline field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	headline: prismic.RichTextField;
	
	/**
	 * Subheadline field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.subheadline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subheadline: prismic.RichTextField;
	
	/**
	 * Primary CTA label field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Request Parts
	 * - **API ID Path**: hero.default.primary.primary_cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	primary_cta_label: prismic.KeyTextField;
	
	/**
	 * Primary CTA link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.primary_cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	primary_cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Secondary CTA label field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Speak to an Engineer
	 * - **API ID Path**: hero.default.primary.secondary_cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	secondary_cta_label: prismic.KeyTextField;
	
	/**
	 * Secondary CTA link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.secondary_cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	secondary_cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Background image (optional) field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero with headline, CTAs and optional background
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Homepage hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *IndustryApplications → Default → Primary*
 */
export interface IndustryApplicationsSliceDefaultPrimary {
	/**
	 * Section heading field in *IndustryApplications → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Industries we serve
	 * - **API ID Path**: industry_applications.default.primary.section_heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	section_heading: prismic.RichTextField;
}

/**
 * Primary content in *IndustryApplications → Items*
 */
export interface IndustryApplicationsSliceDefaultItem {
	/**
	 * Title field in *IndustryApplications → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Offshore
	 * - **API ID Path**: industry_applications.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Short copy field in *IndustryApplications → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: industry_applications.items[].copy
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	copy: prismic.RichTextField;
	
	/**
	 * Link field in *IndustryApplications → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: industry_applications.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Image (optional) field in *IndustryApplications → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: industry_applications.items[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for IndustryApplications Slice
 *
 * - **API ID**: `default`
 * - **Description**: Repeatable industry cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IndustryApplicationsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<IndustryApplicationsSliceDefaultPrimary>, Simplify<IndustryApplicationsSliceDefaultItem>>;

/**
 * Slice variation for *IndustryApplications*
 */
type IndustryApplicationsSliceVariation = IndustryApplicationsSliceDefault

/**
 * IndustryApplications Shared Slice
 *
 * - **API ID**: `industry_applications`
 * - **Description**: Offshore / Marine / Industrial / Mobile
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IndustryApplicationsSlice = prismic.SharedSlice<"industry_applications", IndustryApplicationsSliceVariation>;

/**
 * Primary content in *IndustryApplicationsV2 → Default → Primary*
 */
export interface IndustryApplicationsV2SliceDefaultPrimary {
	/**
	 * Section heading field in *IndustryApplicationsV2 → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Industries we serve
	 * - **API ID Path**: industry_applications_v2.default.primary.section_heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	section_heading: prismic.RichTextField;
}

/**
 * Primary content in *IndustryApplicationsV2 → Items*
 */
export interface IndustryApplicationsV2SliceDefaultItem {
	/**
	 * Title field in *IndustryApplicationsV2 → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Offshore
	 * - **API ID Path**: industry_applications_v2.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Short copy field in *IndustryApplicationsV2 → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: industry_applications_v2.items[].copy
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	copy: prismic.RichTextField;
	
	/**
	 * Link field in *IndustryApplicationsV2 → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: industry_applications_v2.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Image (optional) field in *IndustryApplicationsV2 → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: industry_applications_v2.items[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for IndustryApplicationsV2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Repeatable industry cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IndustryApplicationsV2SliceDefault = prismic.SharedSliceVariation<"default", Simplify<IndustryApplicationsV2SliceDefaultPrimary>, Simplify<IndustryApplicationsV2SliceDefaultItem>>;

/**
 * Slice variation for *IndustryApplicationsV2*
 */
type IndustryApplicationsV2SliceVariation = IndustryApplicationsV2SliceDefault

/**
 * IndustryApplicationsV2 Shared Slice
 *
 * - **API ID**: `industry_applications_v2`
 * - **Description**: Offshore / Marine / Industrial / Mobile (variant)
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IndustryApplicationsV2Slice = prismic.SharedSlice<"industry_applications_v2", IndustryApplicationsV2SliceVariation>;

/**
 * Primary content in *MainPathways → Default → Primary*
 */
export interface MainPathwaysSliceDefaultPrimary {
	/**
	 * Section heading (optional) field in *MainPathways → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_pathways.default.primary.section_heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	section_heading: prismic.RichTextField;
}

/**
 * Primary content in *MainPathways → Items*
 */
export interface MainPathwaysSliceDefaultItem {
	/**
	 * Title field in *MainPathways → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Request Parts
	 * - **API ID Path**: main_pathways.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Description field in *MainPathways → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_pathways.items[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * Link field in *MainPathways → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_pathways.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Icon (optional) field in *MainPathways → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_pathways.items[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	icon: prismic.ImageField<never>;
}

/**
 * Default variation for MainPathways Slice
 *
 * - **API ID**: `default`
 * - **Description**: Repeatable pathway cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MainPathwaysSliceDefault = prismic.SharedSliceVariation<"default", Simplify<MainPathwaysSliceDefaultPrimary>, Simplify<MainPathwaysSliceDefaultItem>>;

/**
 * Slice variation for *MainPathways*
 */
type MainPathwaysSliceVariation = MainPathwaysSliceDefault

/**
 * MainPathways Shared Slice
 *
 * - **API ID**: `main_pathways`
 * - **Description**: Request Parts / Service / Rental pathways
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MainPathwaysSlice = prismic.SharedSlice<"main_pathways", MainPathwaysSliceVariation>;

/**
 * Primary content in *MainPathwaysV2 → Default → Primary*
 */
export interface MainPathwaysV2SliceDefaultPrimary {
	/**
	 * Section heading (optional) field in *MainPathwaysV2 → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_pathways_v2.default.primary.section_heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	section_heading: prismic.RichTextField;
	
	/**
	 * View all label (optional) field in *MainPathwaysV2 → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: View all
	 * - **API ID Path**: main_pathways_v2.default.primary.view_all_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	view_all_label: prismic.KeyTextField;
	
	/**
	 * View all link (optional) field in *MainPathwaysV2 → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_pathways_v2.default.primary.view_all_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	view_all_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *MainPathwaysV2 → Items*
 */
export interface MainPathwaysV2SliceDefaultItem {
	/**
	 * Title field in *MainPathwaysV2 → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Request Parts
	 * - **API ID Path**: main_pathways_v2.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Category (optional) field in *MainPathwaysV2 → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Hydraulics
	 * - **API ID Path**: main_pathways_v2.items[].category
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	category: prismic.KeyTextField;
	
	/**
	 * Description field in *MainPathwaysV2 → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_pathways_v2.items[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * Link field in *MainPathwaysV2 → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_pathways_v2.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Icon (optional) field in *MainPathwaysV2 → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_pathways_v2.items[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	icon: prismic.ImageField<never>;
}

/**
 * Default variation for MainPathwaysV2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Repeatable pathway cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MainPathwaysV2SliceDefault = prismic.SharedSliceVariation<"default", Simplify<MainPathwaysV2SliceDefaultPrimary>, Simplify<MainPathwaysV2SliceDefaultItem>>;

/**
 * Slice variation for *MainPathwaysV2*
 */
type MainPathwaysV2SliceVariation = MainPathwaysV2SliceDefault

/**
 * MainPathwaysV2 Shared Slice
 *
 * - **API ID**: `main_pathways_v2`
 * - **Description**: Request Parts / Service / Rental pathways (variant)
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MainPathwaysV2Slice = prismic.SharedSlice<"main_pathways_v2", MainPathwaysV2SliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum...
	 * - **API ID Path**: rich_text.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<"default", Simplify<RichTextSliceDefaultPrimary>, never>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<"rich_text", RichTextSliceVariation>;

/**
 * Primary content in *StatsBand → Items*
 */
export interface StatsBandSliceDefaultItem {
	/**
	 * Stat number / value field in *StatsBand → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 450HP
	 * - **API ID Path**: stats_band.items[].number
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	number: prismic.KeyTextField;
	
	/**
	 * Stat label field in *StatsBand → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Test Rig Capacity
	 * - **API ID Path**: stats_band.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
}

/**
 * Default variation for StatsBand Slice
 *
 * - **API ID**: `default`
 * - **Description**: Bold stat numbers with labels on a brand-red background
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsBandSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<StatsBandSliceDefaultItem>>;

/**
 * Slice variation for *StatsBand*
 */
type StatsBandSliceVariation = StatsBandSliceDefault

/**
 * StatsBand Shared Slice
 *
 * - **API ID**: `stats_band`
 * - **Description**: Full-width red band with 2–4 key statistics
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsBandSlice = prismic.SharedSlice<"stats_band", StatsBandSliceVariation>;

/**
 * Primary content in *TeamSection → Default → Primary*
 */
export interface TeamSectionSliceDefaultPrimary {
	/**
	 * Eyebrow label (optional) field in *TeamSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Our People
	 * - **API ID Path**: team_section.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;
	
	/**
	 * Section heading field in *TeamSection → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: The Team Behind the Work
	 * - **API ID Path**: team_section.default.primary.section_heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	section_heading: prismic.RichTextField;
	
	/**
	 * Subtext (optional) field in *TeamSection → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_section.default.primary.subtext
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtext: prismic.RichTextField;
}

/**
 * Primary content in *TeamSection → Items*
 */
export interface TeamSectionSliceDefaultItem {
	/**
	 * Photo field in *TeamSection → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_section.items[].photo
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	photo: prismic.ImageField<never>;
	
	/**
	 * Name field in *TeamSection → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: John Smith
	 * - **API ID Path**: team_section.items[].name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Role / Title field in *TeamSection → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Lead Hydraulic Technician
	 * - **API ID Path**: team_section.items[].role
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	role: prismic.KeyTextField;
	
	/**
	 * Short bio (optional) field in *TeamSection → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_section.items[].bio
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	bio: prismic.RichTextField;
	
	/**
	 * LinkedIn URL (optional) field in *TeamSection → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_section.items[].linkedin_url
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	linkedin_url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for TeamSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Grid of team member cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSectionSliceDefault = prismic.SharedSliceVariation<"default", Simplify<TeamSectionSliceDefaultPrimary>, Simplify<TeamSectionSliceDefaultItem>>;

/**
 * Slice variation for *TeamSection*
 */
type TeamSectionSliceVariation = TeamSectionSliceDefault

/**
 * TeamSection Shared Slice
 *
 * - **API ID**: `team_section`
 * - **Description**: Team member grid with photo, name, role and bio
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSectionSlice = prismic.SharedSlice<"team_section", TeamSectionSliceVariation>;

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
	/**
	 * Section heading (optional) field in *Testimonials → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Testimonials
	 * - **API ID Path**: testimonials.default.primary.section_heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	section_heading: prismic.RichTextField;
}

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceDefaultItem {
	/**
	 * Quote field in *Testimonials → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.items[].quote
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	quote: prismic.RichTextField;
	
	/**
	 * Attribution field in *Testimonials → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Name
	 * - **API ID Path**: testimonials.items[].attribution
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	attribution: prismic.KeyTextField;
	
	/**
	 * Role / company (optional) field in *Testimonials → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Offshore Project Manager
	 * - **API ID Path**: testimonials.items[].role_company
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	role_company: prismic.KeyTextField;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Repeatable testimonial items
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<TestimonialsSliceDefaultPrimary>, Simplify<TestimonialsSliceDefaultItem>>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Client quotes
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<"testimonials", TestimonialsSliceVariation>;

/**
 * Primary content in *TestimonialsV2 → Default → Primary*
 */
export interface TestimonialsV2SliceDefaultPrimary {
	/**
	 * Section heading (optional) field in *TestimonialsV2 → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Testimonials
	 * - **API ID Path**: testimonials_v2.default.primary.section_heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	section_heading: prismic.RichTextField;
}

/**
 * Primary content in *TestimonialsV2 → Items*
 */
export interface TestimonialsV2SliceDefaultItem {
	/**
	 * Quote field in *TestimonialsV2 → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials_v2.items[].quote
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	quote: prismic.RichTextField;
	
	/**
	 * Attribution field in *TestimonialsV2 → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Name
	 * - **API ID Path**: testimonials_v2.items[].attribution
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	attribution: prismic.KeyTextField;
	
	/**
	 * Role / company (optional) field in *TestimonialsV2 → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Offshore Project Manager
	 * - **API ID Path**: testimonials_v2.items[].role_company
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	role_company: prismic.KeyTextField;
}

/**
 * Default variation for TestimonialsV2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Repeatable testimonial items
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsV2SliceDefault = prismic.SharedSliceVariation<"default", Simplify<TestimonialsV2SliceDefaultPrimary>, Simplify<TestimonialsV2SliceDefaultItem>>;

/**
 * Slice variation for *TestimonialsV2*
 */
type TestimonialsV2SliceVariation = TestimonialsV2SliceDefault

/**
 * TestimonialsV2 Shared Slice
 *
 * - **API ID**: `testimonials_v2`
 * - **Description**: Client quotes (variant)
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsV2Slice = prismic.SharedSlice<"testimonials_v2", TestimonialsV2SliceVariation>;

/**
 * Primary content in *WhyMicronEagle → Default → Primary*
 */
export interface WhyMicronEagleSliceDefaultPrimary {
	/**
	 * Headline field in *WhyMicronEagle → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Why Micron Eagle
	 * - **API ID Path**: why_micron_eagle.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	headline: prismic.RichTextField;
	
	/**
	 * Body field in *WhyMicronEagle → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: why_micron_eagle.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
}

/**
 * Primary content in *WhyMicronEagle → Items*
 */
export interface WhyMicronEagleSliceDefaultItem {
	/**
	 * Bullet / key stat field in *WhyMicronEagle → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Founded 1990
	 * - **API ID Path**: why_micron_eagle.items[].bullet
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	bullet: prismic.KeyTextField;
}

/**
 * Default variation for WhyMicronEagle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Headline, body, repeatable bullets
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhyMicronEagleSliceDefault = prismic.SharedSliceVariation<"default", Simplify<WhyMicronEagleSliceDefaultPrimary>, Simplify<WhyMicronEagleSliceDefaultItem>>;

/**
 * Slice variation for *WhyMicronEagle*
 */
type WhyMicronEagleSliceVariation = WhyMicronEagleSliceDefault

/**
 * WhyMicronEagle Shared Slice
 *
 * - **API ID**: `why_micron_eagle`
 * - **Description**: Trust block - founded, capabilities, certifications
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhyMicronEagleSlice = prismic.SharedSlice<"why_micron_eagle", WhyMicronEagleSliceVariation>;

/**
 * Primary content in *WhyMicronEagleV2 → Default → Primary*
 */
export interface WhyMicronEagleV2SliceDefaultPrimary {
	/**
	 * Image (left column) field in *WhyMicronEagleV2 → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: why_micron_eagle_v2.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Founded year (shown on image accent - e.g. 1990) field in *WhyMicronEagleV2 → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 1990
	 * - **API ID Path**: why_micron_eagle_v2.default.primary.founded_year
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	founded_year: prismic.KeyTextField;
	
	/**
	 * Headline field in *WhyMicronEagleV2 → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Trusted by industry for over three decades
	 * - **API ID Path**: why_micron_eagle_v2.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	headline: prismic.RichTextField;
	
	/**
	 * Body text field in *WhyMicronEagleV2 → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: why_micron_eagle_v2.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
	
	/**
	 * CTA label (optional) field in *WhyMicronEagleV2 → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Learn about our company
	 * - **API ID Path**: why_micron_eagle_v2.default.primary.cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;
	
	/**
	 * CTA link (optional) field in *WhyMicronEagleV2 → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: why_micron_eagle_v2.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *WhyMicronEagleV2 → Items*
 */
export interface WhyMicronEagleV2SliceDefaultItem {
	/**
	 * Bullet point field in *WhyMicronEagleV2 → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: ISO 9001, 14001 & 45001 certified
	 * - **API ID Path**: why_micron_eagle_v2.items[].bullet
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	bullet: prismic.KeyTextField;
}

/**
 * Default variation for WhyMicronEagleV2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image + headline + body + bullet list + optional CTA
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhyMicronEagleV2SliceDefault = prismic.SharedSliceVariation<"default", Simplify<WhyMicronEagleV2SliceDefaultPrimary>, Simplify<WhyMicronEagleV2SliceDefaultItem>>;

/**
 * Slice variation for *WhyMicronEagleV2*
 */
type WhyMicronEagleV2SliceVariation = WhyMicronEagleV2SliceDefault

/**
 * WhyMicronEagleV2 Shared Slice
 *
 * - **API ID**: `why_micron_eagle_v2`
 * - **Description**: Split layout - image left, content right with bullet points
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhyMicronEagleV2Slice = prismic.SharedSlice<"why_micron_eagle_v2", WhyMicronEagleV2SliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			LayoutDocument,
			LayoutDocumentData,
			LayoutDocumentDataSocialLinksItem,
			LayoutDocumentDataNavLinksItem,
			LayoutDocumentDataFooterLinksItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			BlogGridSlice,
			BlogGridSliceDefaultPrimary,
			BlogGridSliceDefaultItem,
			BlogGridSliceVariation,
			BlogGridSliceDefault,
			CertificationsPartnersSlice,
			CertificationsPartnersSliceDefaultPrimary,
			CertificationsPartnersSliceDefaultItem,
			CertificationsPartnersSliceVariation,
			CertificationsPartnersSliceDefault,
			CertificationsPartnersV2Slice,
			CertificationsPartnersV2SliceDefaultPrimary,
			CertificationsPartnersV2SliceDefaultItem,
			CertificationsPartnersV2SliceVariation,
			CertificationsPartnersV2SliceDefault,
			CoreServicesSlice,
			CoreServicesSliceDefaultPrimary,
			CoreServicesSliceDefaultItem,
			CoreServicesSliceVariation,
			CoreServicesSliceDefault,
			CoreServicesV2Slice,
			CoreServicesV2SliceDefaultPrimary,
			CoreServicesV2SliceDefaultItem,
			CoreServicesV2SliceVariation,
			CoreServicesV2SliceDefault,
			CtaBandSlice,
			CtaBandSliceDefaultPrimary,
			CtaBandSliceDefaultItem,
			CtaBandSliceVariation,
			CtaBandSliceDefault,
			CtaBandV2Slice,
			CtaBandV2SliceDefaultPrimary,
			CtaBandV2SliceDefaultItem,
			CtaBandV2SliceVariation,
			CtaBandV2SliceDefault,
			FaqSlice,
			FaqSliceDefaultPrimary,
			FaqSliceDefaultItem,
			FaqSliceVariation,
			FaqSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			IndustryApplicationsSlice,
			IndustryApplicationsSliceDefaultPrimary,
			IndustryApplicationsSliceDefaultItem,
			IndustryApplicationsSliceVariation,
			IndustryApplicationsSliceDefault,
			IndustryApplicationsV2Slice,
			IndustryApplicationsV2SliceDefaultPrimary,
			IndustryApplicationsV2SliceDefaultItem,
			IndustryApplicationsV2SliceVariation,
			IndustryApplicationsV2SliceDefault,
			MainPathwaysSlice,
			MainPathwaysSliceDefaultPrimary,
			MainPathwaysSliceDefaultItem,
			MainPathwaysSliceVariation,
			MainPathwaysSliceDefault,
			MainPathwaysV2Slice,
			MainPathwaysV2SliceDefaultPrimary,
			MainPathwaysV2SliceDefaultItem,
			MainPathwaysV2SliceVariation,
			MainPathwaysV2SliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			StatsBandSlice,
			StatsBandSliceDefaultItem,
			StatsBandSliceVariation,
			StatsBandSliceDefault,
			TeamSectionSlice,
			TeamSectionSliceDefaultPrimary,
			TeamSectionSliceDefaultItem,
			TeamSectionSliceVariation,
			TeamSectionSliceDefault,
			TestimonialsSlice,
			TestimonialsSliceDefaultPrimary,
			TestimonialsSliceDefaultItem,
			TestimonialsSliceVariation,
			TestimonialsSliceDefault,
			TestimonialsV2Slice,
			TestimonialsV2SliceDefaultPrimary,
			TestimonialsV2SliceDefaultItem,
			TestimonialsV2SliceVariation,
			TestimonialsV2SliceDefault,
			WhyMicronEagleSlice,
			WhyMicronEagleSliceDefaultPrimary,
			WhyMicronEagleSliceDefaultItem,
			WhyMicronEagleSliceVariation,
			WhyMicronEagleSliceDefault,
			WhyMicronEagleV2Slice,
			WhyMicronEagleV2SliceDefaultPrimary,
			WhyMicronEagleV2SliceDefaultItem,
			WhyMicronEagleV2SliceVariation,
			WhyMicronEagleV2SliceDefault
		}
	}
}