// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  main_pathways: dynamic(() => import("./MainPathways")),
  core_services: dynamic(() => import("./CoreServices")),
  industry_applications: dynamic(() => import("./IndustryApplications")),
  why_micron_eagle: dynamic(() => import("./WhyMicronEagle")),
  certifications_partners: dynamic(() => import("./CertificationsPartners")),
  testimonials: dynamic(() => import("./Testimonials")),
  cta_band: dynamic(() => import("./CtaBand")),
  rich_text: dynamic(() => import("./RichText")),
  faq: dynamic(() => import("./Faq")),
  team_section: dynamic(() => import("./TeamSection")),
  blog_grid: dynamic(() => import("./BlogGrid")),
  main_pathways_v2: dynamic(() => import("./MainPathwaysV2")),
  core_services_v2: dynamic(() => import("./CoreServicesV2")),
  industry_applications_v2: dynamic(() => import("./IndustryApplicationsV2")),
  why_micron_eagle_v2: dynamic(() => import("./WhyMicronEagleV2")),
  certifications_partners_v2: dynamic(() => import("./CertificationsPartnersV2")),
  testimonials_v2: dynamic(() => import("./TestimonialsV2")),
  cta_band_v2: dynamic(() => import("./CtaBandV2")),
  stats_band: dynamic(() => import("./StatsBand")),
};
